### ISSUE TITLE
Unable to edit wizard builder questions in django admin

### ISSUE THREAD

**Issue by scattermagic** [project-callisto/django-wizard-builder#184]
When inside django admin, all questions and answer models (multi choice, single line text, and so on) give an error when user tries to edit them. 
<img width="1085" alt="screen shot 2017-10-11 at 12 12 21 pm" src="https://user-images.githubusercontent.com/32528545/31458476-752c5800-ae7d-11e7-90da-f72215cd4a6c.png">

**Comment by lynncyrin** [comment]
I can't reproduce this on https://django-wizard-builder.herokuapp.com, and also `nesting_server_data` isn't a url that wizard builder defines specifically.

A search gives me this https://stackoverflow.com/questions/31254118/django-nested-admin-urls-not-loading so the issue likely lies in your url configuration for `django-nested-admin`

As an aside, I'm not sure that this code works in python 3.5 as opposed to python 3.6

**Comment by scattermagic** [comment]
a few things we ran into:
1. The original issue with admin
2. When submitting a report to matching in the callisto, and then selecting withdraw, we get a very similar error (image attached). 
3. When doing the same process on the demo app on heroku, we get a 500 error once trying to withdraw. It would be interesting to see if it also is an error with nesting_server_data in heroku.

One curious spot in the wizard builder codebase is 
wizard_builder / admin / base.py
in the DowncastedAdmin class
on line 22 we see a reverse_url being generated, maybe this is the source of some broken urls?

Anyways, here is the image of the error we got when we tried to withdraw a report in callisto
![screen shot 2017-10-17 at 4 15 10 pm](https://user-images.githubusercontent.com/32528545/31692591-99ffca02-b357-11e7-9795-c6451db431f3.png)


![](https://files.slack.com/files-pri/T0B8YFA2Y-F7KSNRJSY/screen_shot_2017-10-17_at_4.15.10_pm.png)

**Comment by lynncyrin** [comment]
Withdrawing from matching https://callisto-core.herokuapp.com is giving an error for me right now, but that error is

```
Oct 18 16:47:09 callisto-core app/web.1: Traceback (most recent call last): 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner 
Oct 18 16:47:09 callisto-core app/web.1:     response = get_response(request) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response 
Oct 18 16:47:09 callisto-core app/web.1:     response = self._get_response(request) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response 
Oct 18 16:47:09 callisto-core app/web.1:     response = self.process_exception_by_middleware(e, request) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response 
Oct 18 16:47:09 callisto-core app/web.1:     response = response.render() 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/response.py", line 107, in render 
Oct 18 16:47:09 callisto-core app/web.1:     self.content = self.rendered_content 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content 
Oct 18 16:47:09 callisto-core app/web.1:     content = template.render(context, self._request) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render 
Oct 18 16:47:09 callisto-core app/web.1:     return self.template.render(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 207, in render 
Oct 18 16:47:09 callisto-core app/web.1:     return self._render(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render 
Oct 18 16:47:09 callisto-core app/web.1:     return self.nodelist.render(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render 
Oct 18 16:47:09 callisto-core app/web.1:     bit = node.render_annotated(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated 
Oct 18 16:47:09 callisto-core app/web.1:     return self.render(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render 
Oct 18 16:47:09 callisto-core app/web.1:     return compiled_parent._render(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 199, in _render 
Oct 18 16:47:09 callisto-core app/web.1:     return self.nodelist.render(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render 
Oct 18 16:47:09 callisto-core app/web.1:     bit = node.render_annotated(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated 
Oct 18 16:47:09 callisto-core app/web.1:     return self.render(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render 
Oct 18 16:47:09 callisto-core app/web.1:     result = block.nodelist.render(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 990, in render 
Oct 18 16:47:09 callisto-core app/web.1:     bit = node.render_annotated(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated 
Oct 18 16:47:09 callisto-core app/web.1:     return self.render(context) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/defaulttags.py", line 458, in render 
Oct 18 16:47:09 callisto-core app/web.1:     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/urls/base.py", line 91, in reverse 
Oct 18 16:47:09 callisto-core app/web.1:     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))) 
Oct 18 16:47:09 callisto-core app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix 
Oct 18 16:47:09 callisto-core app/web.1:     raise NoReverseMatch(msg) 
Oct 18 16:47:09 callisto-core app/web.1: django.urls.exceptions.NoReverseMatch: Reverse for 'None' not found. 'None' is not a valid view function or pattern name. 
```
